### ISSUE TITLE
Unable to achive read-only mode with plugin

### ISSUE THREAD

**Issue by cybernotic** [marcusgreen/local_read_only#1]
Hi there,
Hopefully you will be able to help me with this.
I recently installed the plugin but kept on thinking that there must be something that I am missing?
I was able to enable 'Read Only Mode' within the admin settings and add a simple message then save changes. The alert message appeared but I was able to accomplish standard tasks (uploaded a submission and saved it) which would write to the database logged in as a student so I am assuming it was not in read only mode.
When I visited local_read_only_status, local_read_only_alert_banner or local_read_only_capabilities I received this error message:

`Section error!
    line 494 of /lib/setuplib.php: moodle_exception thrown
    line 26 of /admin/settings.php: call to print_error()`

Are there any step by step instructions you could supply which will insure the correct installation process?
Are there some test cases to show that it is actually working on a version of Moodle?
Thanks for your time.

Regards
David

**Comment by marcusgreen** [comment]
Slide 16 may help
https://assets.moodlemoot.org/sites/91/20190424131255/3.-Read-Only-Moodle-Marcus-Green-_-Titus-Learning.pdf

If not post again.

**Comment by cybernotic** [comment]
Hi Marcus 
I have followed the steps successfully, copied mysqlior_native_moodle_database.php to the correct path updated the config.php file but still I am able to update the database login on as a student, and I still receive those error messages when I visited local_read_only_status, local_read_only_alert_banner or local_read_only_capabilities.

Is there any working cases of this  plugin working on any version of Moodle?
Thanks
David

**Comment by cybernotic** [comment]
Hi Marcus, thank you for getting back to me via email, I have created a new Moodle build v37 to start some fresh tests and all standard tasks which I have tested has worked as expected, please see the test result attachment. 
You mentioned before in your email that you were working on the admin problem, banner and the quiz issue.
Currently any student role can attempt quizzes and the changes will be saved to the database, do you have any updates on these if possible?

We have a long list of plugins for our UCL Moodle site, does this mean the database tables for these plugins will need to be added to the exclusion list? Is this something that we can easily do within the code? 

Thanks for your help.
Regards
David


[MoodleReadOnly.docx](https://github.com/marcusgreen/local_read_only/files/3377237/MoodleReadOnly.docx)

**Comment by cybernotic** [comment]
closed accidetly

**Comment by cybernotic** [comment]
Hi @hitteshahuja, and Marcus,

I commented out the quiz tables in the array within mysqliro_native_moodle_database.php, now the quizes are read only. IT has not affected the functionality of the quizes or caused an issue, please can you tell me what were the reasons behind excluding these tables?

Regards
David

**Comment by marcusgreen** [comment]
I added the quiz table list and although yesterday I suggested it was to do with being able to traverse existing quizzes, it may well have been an experiment that is unnecessary for normal read-only use.

**Comment by cybernotic** [comment]
Ok thanks a lot for that Marcus, my team are going to perform more tests on a pre prody moodle instance just to cover all areas but the main areas that needs to read-only are working as expected so this issue can be closed.
