### ISSUE TITLE
Course sections can be deleted in read-only mode

### ISSUE THREAD

**Issue by ghost** [marcusgreen/local_read_only#5]
With read-only mode enabled, a course section can be deleted.

Steps to recreate issue:
1 - Have a Moodle course with one or multiple sections
2 - Have a user enrolled onto the course with the permissions to edit or delete sections
3 - Ensure site is in read-only mode
4 - Navigate to Moodle course
5 - Turn editing on
6 - Delete a section from the course
7 - Refresh the page or turn editing off

I expected the course section to be 'deleted' until the page was refreshed, like it does when deleting an activity or resource, but the section has been deleted entirely and the action of deleting is visible within the course logs.

**Comment by marcusgreen** [comment]
Thanks John, I will investigate

**Comment by marcusgreen** [comment]
I have reproduced this issue and I have some ideas why it may be happening. I will let you know when I have made further progress

**Comment by marcusgreen** [comment]
I have made some changes to branch marcus. The warning message shows up in many more places not just the login form and you should no longer be able to delete course sections or move things around the course. You can drag activities up and down the course page, but on refresh they revert to where they were.  You can test this out as a teacher at.
https://vledevelop.co.uk/ro
username
t1
password
Password1!
Let me know what you think

**Comment by marcusgreen** [comment]
I would like to make it possible to toggle read-only mode from the command line, but I have not worked out how to do that just yet.

**Comment by marcusgreen** [comment]
see the cli folder for toggling from the command line as in php toggle.php

**Comment by marcusgreen** [comment]
The fix for this is the addition of the set_field function in db.php. This is in the master branch so I am closing this issue now.
