### ISSUE TITLE
Question bank not saved

### ISSUE THREAD

**Issue by sorincocorada** [marcusgreen/local_read_only#6]
After installing and activating the read only_module our users complained that when they perform a backup of a course the question bank is not saved(questuions.xml from the mbz archive contains no questions).
The same happens if:
- backup is performed using the administrator account
- read only is deactivated

The question bank was included again only if the read_only module was deactivated and uninstalled

**Comment by marcusgreen** [comment]
Thank you for reporting this. I will investigate.

**Comment by sorincocorada** [comment]
> Thank you for reporting this. I will investigate.

Thanks! 
If you need further details or you think I can help somehow just let me know.

**Comment by marcusgreen** [comment]
Have installed on 3.9 and am about to do a course backup, will let you know results.

**Comment by marcusgreen** [comment]
I have done a backup as admin and as a teacher and the file size is different, when I open them it looks like the file question.xml is missing. It almost certainly makes no difference, but could you confirm what version of Moodle you are working with.

**Comment by sorincocorada** [comment]
First the users found the problem on 3.7.2. Then I found it also on 3.5.2. 
I have also tested on 3.8.2, and it's the same

**Comment by marcusgreen** [comment]
I will continue to test against 3.9 and go to earlier versions when I know more.

**Comment by sorincocorada** [comment]
ok, I will then also update the 3.8.2 test instance to the latest one, just to be prepared for testing

**Comment by marcusgreen** [comment]
I might go a bit quiet for the next 8 hours and then pick it up after that. Am on UK time, what are you on?

**Comment by sorincocorada** [comment]
No problem. My timezone is UTC+2

**Comment by marcusgreen** [comment]
I think I understand the cause of the issue, I am now trying to work out the best fix.

**Comment by marcusgreen** [comment]
I have created an update that should fix the problem. See the release notes.
https://github.com/marcusgreen/local_read_only/blob/master/changelog.md

**Comment by sorincocorada** [comment]
Hi,
I have installed the updated version on Moodle 3.7.2, it seems to work correctly: the questions are now included into the backup archive.
Thank you very much
